package POO;

// CLASSE PRINCIPAL "MAIN", ONDE O CÓDIGO SERÁ EXECUTADO
public class Main {

	// MÉTODO PRINCIPAL QUE IRÁ INICIAR O PROGRAMA
	public static void main(String[] args) {
		
		// PUBLIC - SIGNIFICA QUE O MÉTODO É VISÍVEL PARA O JAVA EXECUTAR FORA DA CLASSE
		// STATIC - PERMITE QUE O MÉTODO SEJA EXECUTADO SEM PRECISAR CRIAR UM OBJETO DA CLASSE
		// VOID - INDICA QUE O MÉTODO NÃO RETORNA VALOR
		// STRING[] ARGS - É UM ARRAY DE STRINGS USADO PARA RECEBER DADOS DO USUÁRIO PELA LINHA DE COMANDO (GERALMENTE OPCIONAL)

	}
	
	// MAIN É ONDE O PROGRAMA COMEÇA A RODAR
	// SERVE PARA TESTAR E EXECUTAR O CÓDIGO DE OUTRAS CLASSES
	// GERALMENTE CONTÉM O MÉTODO MAIN() QUE CHAMA OBJETOS E MÉTODOS DE OUTRAS PARTES DO SISTEMA

}
